/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StudentRouteImport } from './routes/student'
import { Route as QuizAttemptIdRouteImport } from './routes/quiz.$attemptId'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherQuizQuizIdRouteImport } from './routes/teacher.quiz.$quizId'
import { Route as TeacherResultsQuizIdRouteImport } from './routes/teacher.results.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizAttemptIdRoute = QuizAttemptIdRouteImport.update({
  id: '/quiz/$attemptId',
  path: '/quiz/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherQuizQuizIdRoute = TeacherQuizQuizIdRouteImport.update({
  id: '/teacher/quiz/$quizId',
  path: '/teacher/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherResultsQuizIdRoute = TeacherResultsQuizIdRouteImport.update({
  id: '/teacher/results/$quizId',
  path: '/teacher/results/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/student': typeof StudentRoute
  '/quiz/$attemptId': typeof QuizAttemptIdRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/quiz/$quizId': typeof TeacherQuizQuizIdRoute
  '/teacher/results/$quizId': typeof TeacherResultsQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/student': typeof StudentRoute
  '/quiz/$attemptId': typeof QuizAttemptIdRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/quiz/$quizId': typeof TeacherQuizQuizIdRoute
  '/teacher/results/$quizId': typeof TeacherResultsQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/student': typeof StudentRoute
  '/quiz/$attemptId': typeof QuizAttemptIdRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/quiz/$quizId': typeof TeacherQuizQuizIdRoute
  '/teacher/results/$quizId': typeof TeacherResultsQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/quiz/$attemptId'
    | '/teacher/'
    | '/teacher/quiz/$quizId'
    | '/teacher/results/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/student'
    | '/quiz/$attemptId'
    | '/teacher'
    | '/teacher/quiz/$quizId'
    | '/teacher/results/$quizId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/quiz/$attemptId'
    | '/teacher/'
    | '/teacher/quiz/$quizId'
    | '/teacher/results/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  StudentRoute: typeof StudentRoute
  QuizAttemptIdRoute: typeof QuizAttemptIdRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherQuizQuizIdRoute: typeof TeacherQuizQuizIdRoute
  TeacherResultsQuizIdRoute: typeof TeacherResultsQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$attemptId': {
      id: '/quiz/$attemptId'
      path: '/quiz/$attemptId'
      fullPath: '/quiz/$attemptId'
      preLoaderRoute: typeof QuizAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/quiz/$quizId': {
      id: '/teacher/quiz/$quizId'
      path: '/teacher/quiz/$quizId'
      fullPath: '/teacher/quiz/$quizId'
      preLoaderRoute: typeof TeacherQuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/results/$quizId': {
      id: '/teacher/results/$quizId'
      path: '/teacher/results/$quizId'
      fullPath: '/teacher/results/$quizId'
      preLoaderRoute: typeof TeacherResultsQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  StudentRoute: StudentRoute,
  QuizAttemptIdRoute: QuizAttemptIdRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherQuizQuizIdRoute: TeacherQuizQuizIdRoute,
  TeacherResultsQuizIdRoute: TeacherResultsQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
